✨Feature/plugin non breaking spaces
AckeeCZ/lokse pull request #55
Opened 2021-10-20 11:19 UTC by filip-dot-cube

— Adds plugin for replacing single-letter characters with non-breaking spaces

— So far only for Czech language, however patterns list could be extend via plugin options

— Later on we could base general find and replace plugin on this one

2021-11-04 13:04 UTC, filip-dot-cube commented
https://www.youtube.com/watch?v=ZurS1L3cV48

2021-11-05 07:38 UTC, horaklukas requested changes
Minor changes to make, but otherwise really good job 👏

2021-11-05 07:38 UTC, horaklukas commented on packages/plugin-non-breaking-spaces/src/utils.ts
> +import { CustomPatterns } from ".";
Are you sure about this import from `'.'` ? 🙂

2021-11-05 07:38 UTC, horaklukas commented on packages/plugin-non-breaking-spaces/src/__tests__/index.test.ts
> +import Transformer from "../../../core/lib/transformer/json";
Please don't break packages encapsulation 🙏 

```suggestion
import { transformersByFormat, OutputFormat } from "@lokse/core";

const Transformer = transformersByFormat[OutputFormat.JSON];
```

2021-11-05 07:38 UTC, horaklukas commented on packages/plugin-non-breaking-spaces/src/index.ts
> +        );
2. Ok, I understand, lets keep it as it is, I didn't realize the gramatics differencies the feature is based on. 

We could maybe provide default definitions for some most used languages like EN/DE. Please create an enhancement ticket for it 🙏

2021-11-05 15:53 UTC, filip-dot-cube commented on packages/plugin-non-breaking-spaces/src/index.ts
> +        );
Alright, makes sense.

https://github.com/AckeeCZ/lokse/issues/57

2021-11-05 16:02 UTC, filip-dot-cube commented
> Minor changes to make, but otherwise really good job 👏 after that you're good to merge it 😉

Thanks :)

2021-11-05 16:02 UTC, merged